version: "3.6"
services:
    postgres:
        image: postgres:12
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespassword
    graphql-engine:
        image: hasura/graphql-engine:v1.3.2
        ports:
            - "8080:8080"
        depends_on:
            - "postgres"
        restart: always
        environment:
            ## enable this to run postgres in local
            # HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres

            ## enable this to run postgres in cloud
            HASURA_GRAPHQL_DATABASE_URL: postgres://lztfrqervmuvtn:1207c9eee0d4892ef47a41c972e6d0ec688bf9fce08668af2d7576f334801c64@ec2-52-204-20-42.compute-1.amazonaws.com:5432/d7eaie1jj4atrv
            ## enable the console served by server
            HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
            ## enable debugging mode. It is recommended to disable this in production
            HASURA_GRAPHQL_DEV_MODE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ## uncomment next line to set an admin secret
            HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
volumes:
    db_data:
